[alias]
xtask = "run --target-dir target/xtask --color always --package xtask --bin xtask --"

# On CPU, run light suite by default
test-cpu = "test --release --features cubecl/cpu"

# On GPU, run basic suite by default
test-cuda = "test --release --features cubecl/cuda,basic"
test-rocm = "test --release --features cubecl/rocm,basic"
test-wgpu = "test --release --features cubecl/wgpu,basic"
test-vulkan = "test --release --features cubecl/vulkan,basic"
test-metal = "test --release --features cubecl/metal,basic"

test-cpu-light = "test --release --features cubecl/cpu"
test-cuda-light = "test --release --features cubecl/cuda"
test-rocm-light = "test --release --features cubecl/rocm"
test-wgpu-light = "test --release --features cubecl/wgpu"
test-vulkan-light = "test --release --features cubecl/vulkan"
test-metal-light = "test --release --features cubecl/metal"

test-cpu-basic = "test --release --features cubecl/cpu,basic"
test-cuda-basic = "test --release --features cubecl/cuda,basic"
test-rocm-basic = "test --release --features cubecl/rocm,basic"
test-wgpu-basic = "test --release --features cubecl/wgpu,basic"
test-vulkan-basic = "test --release --features cubecl/vulkan,basic"
test-metal-basic = "test --release --features cubecl/metal,basic"

test-cpu-extended = "test --release --features cubecl/cpu,extended"
test-cuda-extended = "test --release --features cubecl/cuda,extended"
test-rocm-extended = "test --release --features cubecl/rocm,extended"
test-wgpu-extended = "test --release --features cubecl/wgpu,extended"
test-vulkan-extended = "test --release --features cubecl/vulkan,extended"
test-metal-extended = "test --release --features cubecl/metal,extended"

test-cpu-full = "test --release --features cubecl/cpu,full"
test-cuda-full = "test --release --features cubecl/cuda,full"
test-rocm-full = "test --release --features cubecl/rocm,full"
test-wgpu-full = "test --release --features cubecl/wgpu,full"
test-vulkan-full = "test --release --features cubecl/vulkan,full"
test-metal-full = "test --release --features cubecl/metal,full"
